num1 = int(input("Num1 :"))
num2 = int(input("Num2 :"))
num3 = int(input("Num3 :"))
max_num = max(num1,num2,num3)
min_num = min(num1,num2,num3)
print("Maximum number is ",max_num)
print("Minimum number is ", min_num)